export const products = [
    {
        id: 1,
        name: "Iphone 11",
        category: "Iphone",
        storage: "128GB",
        price: 30,
        image: "/images/products/11.png",
        isCart: false,
        description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
    },
    {
        id: 2,
        name: "Iphone 12 Pro Max",
        category: "Iphone",
        storage: "256GB",
        price: 741,
        image: "/images/products/12prmx.png",
        isCart: false,
        description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
    },
    {
        id: 3,
        name: "Xiaomi 13 Ultra",
        category: "Xiaomi",
        storage: "512GB",
        price: 17,
        image: "/images/products/13Ultra.png",
        isCart: false,
        description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
        id: 4,
        name: "Xiaomi 12T",
        category: "Xiaomi",
        storage: '512GB',
        price: 16,
        image: "/images/products/xiaomi12t.png",
        isCart: false,
        description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
    },
    {
        id: 5,
        name: "Realme GT Neo 5 SE",
        category: "Realme",
        storage: '256GB',
        price: 10,
        image: "/images/products/realmegtneo5se.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 6,
        name: "Realme 11 Pro+ 5G",
        category: "Realme",
        storage: '512GB',
        price: 10,
        image: "/images/products/realme11pro+5g.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 7,
        name: "Samsung Galaxy S23 FE",
        category: "Samsung",
        storage: '128GB',
        price: 10,
        image: "/images/products/samsungs23fe.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 8,
        name: "Samsung Galaxy S23 Ultra",
        category: "Samsung",
        storage: '256GB',
        price: 10,
        image: "/images/products/samsungs23ultra.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    }
];